languageCode = 'en'
defaultContentLanguage = "en"
baseurl = 'https://dmscherr.com'
theme = 'hugo-coder'
title = 'Code and Things'
enableEmoji = true

[pagination]
pagerSize = 6

[params]
    author = "Daniel Scherr"
    avatarURL = "/images/avatar.webp"
    dateFormat = "January 2, 2006"
    since = 2015
    colorScheme = "dark"
    description = "This is a blog for me to write down my thoughts about projects I work on."

[taxonomies]
tag = "tags"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Mosherr"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/dmscherr"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "pages/about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Resume"
weight = 3
url = "pages/resume/"

[[languages.en.menu.main]]
name = "Tags"
weight = 4
url = "tags"

[deployment]
    [[deployment.targets]]
    name = 'production'
    url = 's3://dmscherr.com?region=us-west-1'
